const cards=[...document.querySelectorAll('.film-card')];
const filters=[...document.querySelectorAll('[data-archive-filter]')];
const search=document.querySelector('#film-search');
let active='All';
function applyFilters(){let count=0;const term=(search?.value||'').toLowerCase().trim();cards.forEach(card=>{card.hidden=!(active==='All'||card.dataset.format===active)||!card.textContent.toLowerCase().includes(term);if(!card.hidden)count++;});const counter=document.querySelector('#film-count');if(counter)counter.textContent=`${count} of ${cards.length} films`;const empty=document.querySelector('#no-films');if(empty)empty.hidden=count>0;}
filters.forEach(button=>button.addEventListener('click',()=>{active=button.dataset.archiveFilter;filters.forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});applyFilters();}));
search?.addEventListener('input',applyFilters);
const modal=document.querySelector('#archive-player');let returnFocus;
if(modal){const video=modal.querySelector('video');document.querySelectorAll('[data-film-src]').forEach(button=>button.addEventListener('click',()=>{returnFocus=button;modal.querySelector('h2').textContent=button.dataset.title;modal.querySelector('.film-context').textContent=button.dataset.idea;const link=modal.querySelector('.source-link');link.href=button.dataset.filmSrc;video.src=button.dataset.filmSrc;video.poster=button.querySelector('img').src;video.setAttribute('aria-label',button.dataset.title);modal.showModal();document.body.classList.add('modal-open');video.play().catch(()=>{});}));modal.querySelector('button').addEventListener('click',()=>modal.close());modal.addEventListener('close',()=>{video.pause();video.removeAttribute('src');video.load();document.body.classList.remove('modal-open');returnFocus?.focus();});modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)modal.close();}});video.addEventListener('error',()=>{modal.querySelector('.film-context').textContent='This hosted video could not load. Try the original video link below. The file is also preserved in the private portfolio archive.';});}
applyFilters();
